config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets do
    member do
      get :assign
      get :hold
      get :complete
      get :cancel
      post :reply
    end
  end

  authenticated :user do
    resources :users

    get 'settings', to: 'users#settings'
    put 'password', to: 'users#password'
    # root to: 'tickets#index'
  end

  root to: 'tickets#new'
end

app/models/department.rb
class Department
  include Mongoid::Document

  field :name, type: String

  has_many :tickets
  has_many :users
end

app/models/history.rb
class History
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  belongs_to :ticket
  belongs_to :user

  field :from_state, type: Symbol
  field :to_state, type: Symbol

  #TODO: Extract to observer
  after_create :send_email, unless: -> { Rails.env.test? }

  private

  def send_email
    TicketMailer.ticket_updated(self).deliver
  end
end

app/models/screenshot.rb
class Screenshot
  include Mongoid::Document
  include Mongoid::Paperclip

  embedded_in :ticket

  has_mongoid_attached_file :image

  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/ticket.rb
class Ticket
  include Mongoid::Document
  include Mongoid::Timestamps
  include StateMachine::Integrations::Mongoid

  embeds_many :screenshots, cascade_callbacks: true
  belongs_to :department
  belongs_to :assignee, class_name: 'User'
  has_many :histories

  # Submitter info
  # TODO: Think about extracting to a separate class and indexing
  field :user_email, type: String
  field :user_name, type: String

  # TODO: generate, index
  field :uid, type: String

  # Ticket data
  field :subject, type: String
  field :body, type: String

  field :reply, type: String

  field :state, type: Symbol
  attr_accessor :prev_state

  validates_uniqueness_of :uid
  before_validation :generate_uid, on: :create

  STATES = [:submitted, :assigned, :holded, :cancelled, :completed]

  def files= files
    files.each do |file|
      begin
        screenshots.build(image: file)
      rescue
        self.errors.add :screenshots, I18n.t('ticket.errors.image')
      end
    end
  end

  state_machine :state, initial: :submitted do
    event :assign do
      transition :submitted => :assigned
    end

    event :hold do
      transition :assigned => :holded
    end

    event :cancel do
      transition [:assigned, :holded] => :cancelled
    end

    event :complete do
      transition [:assigned, :holded] => :completed
    end

    before_transition do |object|
      object.prev_state = object.state
    end
  end

  before_update do
    if self.assignee_id_changed?
      self.histories.create(from_state: self.state, to_state: self.state, user: self.assignee)
    end
    if self.prev_state.present?
      $redis.publish 'state-change', {uid: self.uid, state: self.state}.to_json
      self.histories.create(from_state: self.prev_state, to_state: self.state, user: self.assignee)
    end
  end

  def to_param
    self.uid
  end

  private

  #TODO: find less ugly way to do this. This may be non-thread-safe
  def generate_uid
    def tri vals
      "#{vals.sample}#{vals.sample}#{vals.sample}"
    end
    chars = ("A".."Z").to_a
    numbers = ("0".."9").to_a
    self.uid = loop do
      uid = "#{tri(chars)}-#{tri(numbers)}-#{tri(chars)}-#{tri(numbers)}-#{tri(chars)}"
      break uid unless Ticket.where(uid: uid).exists?
    end
  end
end

app/models/user.rb
class User
  include Mongoid::Document

  has_many :tickets, inverse_of: 'assignee'

  devise :database_authenticatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  field :name, type: String

  ROLES = [:member, :admin]

  field :role, type: Symbol, default: :member

  ROLES.each do |role|
    class_eval <<-eos
      def #{role}?
        self.role == :#{role}
      end
    eos
  end


  # From all the hacks, it seemed the best one.
  # Furthermore, it does not properly work with tests. *facepalm.jpg*
  # https://github.com/plataformatec/devise/issues/2949
  unless Rails.env.test?
    class << self
      def serialize_from_session(key, salt)
        record = to_adapter.get(key[0]["$oid"])
        record if record && record.authenticatable_salt == salt
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_admin!
    authenticate_user!
    redirect_to :root unless current_user.admin?
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!, except: [:new, :show]
  before_action :load_ticket, only: [:show, :assign, :cancel, :hold, :complete, :reply]
  before_action :check_assigned, only: [:cancel, :hold, :complete, :reply]

  helper_method :assigned_to_user?

  def index
    params[:state] ||= :submitted
    @tickets = Ticket.all
    @tickets = @tickets.where(state: params[:state]) unless params[:state] == 'all'
    @tickets = @tickets.page(params[:page])
  end

  def show
  end

  def reply
    @ticket.reply = params[:reply]
    if @ticket.save
      TicketMailer.ticket_replied(@ticket).deliver
    end
    redirect_to :back
  end

  def assign
    @ticket.assignee = current_user
    @ticket.assign!
    redirect_to :back
  end

  def hold
    @ticket.hold!
    redirect_to :back
  end

  def cancel
    @ticket.cancel!
    redirect_to :back
  end

  def complete
    @ticket.complete!
    redirect_to :back
  end

  def new
    @ticket = Ticket.new
  end

  def create
    ticket = Ticket.new permitted_params

    files = params[:files]
    ticket.files = files if files.present?
    if ticket.save
      # TODO: Investigate rails 4 mailer
      TicketMailer.ticket_created(ticket).deliver
      flash.notice = t('ticket.info.created')
    else
      flash.alert = t('ticket.info.failed')
    end
    redirect_to :root
  end

  def assigned_to_user? ticket
    current_user.present? && (ticket.assignee == current_user)
  end

  private

  def load_ticket
    @ticket = Ticket.find_by(uid: params[:id])
  end

  def check_assigned
    unless assigned_to_user? @ticket
      flash[:alert] = t 'site.errors.unassigned'
      redirect_to :root
    end
  end

  def permitted_params
    params.require(:ticket).permit(:user_name, :user_email, :department_id, :subject, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin!, except: [:password, :settings]

  def index
    @users = User.all.page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new permitted_params
    if @user.save
      flash[:notice] = t 'user.info.created'
    else
      flash[:alert] = t 'user.info.failure'
    end
    redirect_to action: :index
  end

  def settings
  end

  def password
    current_user.password = params[:password]
    current_user.password_confirmation = params[:password_confirmation]
    if current_user.save
      flash[:notice] = t 'user.info.pass_changed'
    else
      flash[:alert] = t 'user.info.failure'
    end
    redirect_to :root
  end

  private

  def permitted_params
    params.require(:user).permit(:email, :password, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def image_thumbs ticket
    # TODO: print thumbs
  end
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Helpdesk
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
  %body
    %nav
      %div.login-panel
        - if current_user.present?
          = t 'site.logged_message', username: current_user.name
          = link_to t('site.logout'), destroy_user_session_path

          %ul
            %li= link_to t('site.tickets'), tickets_path
            %li= link_to t('site.settings'), settings_path

            - if current_user.admin?
              %li= link_to t('site.users'), users_path
        - else
          = link_to t('site.login'), user_session_path

        = link_to t('site.new_ticket'), new_ticket_path

      - if flash[:notice].present?
        %div.flash-notice= flash[:notice]

      - if flash[:alert].present?
        %div.flash-alert= flash[:alert]

    = yield

app/views/tickets/_reply_form.html.haml
= form_tag reply_ticket_path(ticket) do
  = text_field_tag :reply
  = submit_tag t('ticket.actions.reply')

app/views/tickets/index.html.haml
%h2 Show only:
%nav
  %ul
    - [:all, :submitted, :assigned, :holded, :cancelled, :confirmed].each do |state|
      %li= link_to state.to_s.capitalize, params.merge(state: state)

%table
  %tr
    %th= t 'ticket.table.uid'
    %th= t 'ticket.table.subject'
    %th= t 'ticket.table.body'
    %th= t 'ticket.table.state'
    %th= t 'ticket.table.screenshots'
    %th= t 'ticket.table.actions'
  - @tickets.each do |ticket|
    %tr
      %td= link_to ticket.uid, ticket_path(ticket)
      %td= ticket.subject
      %td= ticket.body
      %td= ticket.state
      %td= image_thumbs ticket
      %td
        - if ticket.assignee?
          - if assigned_to_user? ticket
            = t 'ticket.info.assigned.me'
          - else
            = t 'ticket.info.assigned.to', name: ticket.assignee.name
        - else
          = link_to t('ticket.actions.assign'), assign_ticket_path(ticket)

= paginate @tickets

app/views/tickets/new.html.haml
= form_tag tickets_path, method: :post, multipart: true do |f|
  %div.label= t 'ticket.form.email'
  = text_field :ticket, :user_email
  %div.label= t 'ticket.form.name'
  = text_field :ticket, :user_name
  %div.label= t 'ticket.form.subject'
  = text_field :ticket, :subject
  %div.label= t 'ticket.form.body'
  = text_area :ticket, :body
  %div.label= t 'ticket.form.files'
  = file_field_tag "files[]", multiple: true
  = submit_tag t('ticket.form.send')

app/views/tickets/show.html.haml
%div.actions
  - if assigned_to_user? @ticket
    - case @ticket.state
    - when :assigned
      = link_to t('ticket.actions.hold'), hold_ticket_path(@ticket)
      = link_to t('ticket.actions.cancel'), cancel_ticket_path(@ticket)
      = link_to t('ticket.actions.complete'), complete_ticket_path(@ticket)
    - when :holded
      = link_to t('ticket.actions.cancel'), cancel_ticket_path(@ticket)
      = link_to t('ticket.actions.complete'), complete_ticket_path(@ticket)
  - elsif !@ticket.assignee?
    = link_to t('ticket.actions.assign'), assign_ticket_path(@ticket)

%h1= @ticket.subject
%div= @ticket.uid

%p= @ticket.body

%p= @ticket.reply
- if assigned_to_user? @ticket
  = render partial: 'reply_form', locals: { ticket: @ticket }

%h2= t 'ticket.table.state'
%div.dynamic-state{ data: {uid: @ticket.uid} }= @ticket.state

- @ticket.screenshots.each do |screenshot|
  = image_tag screenshot.image.url

app/views/users/index.html.haml
%table
  %tr
    %th= t 'user.table.name'
    %th= t 'user.table.role'
    %th= t 'user.table.email'
    %th= t 'user.table.actions'
  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.role
      %td= user.email
      %td
        /Some actions here

app/views/users/new.html.haml
= form_for @user do |f|
  %div.label= t 'user.form.name'
  = f.text_field :name
  %div.label= t 'user.form.email'
  = f.text_field :email
  %div.label= t 'user.form.password'
  = f.password_field :password
  %div.label= t 'user.form.password_confirmation'
  = f.password_field :password_confirmation
  %div.label= t 'user.form.role'
  = f.select :role, options_for_select([:member, :admin])
  = f.submit t('user.form.submit')

app/views/users/settings.html.haml
%div
  %h1= t 'user.change_password'
  = form_tag password_path, method: :put do
    = t 'user.new_password'
    = password_field_tag 'password'
    = t 'user.new_password_confirmation'
    = password_field_tag 'password_confirmation'
    = submit_tag t('user.change_password')